config/routes.rb
DssEvote::Application.routes.draw do
  resources :surveys

  get "site/index"

  get "site/contact"

  root :to => "site#index"

end

app/models/ballot.rb
class Ballot < ActiveRecord::Base
end

app/models/eligibility.rb
class Eligibility < ActiveRecord::Base
  belongs_to :survey
end

app/models/group.rb
class Group < ActiveResource::Base
  self.site = "http://169.237.156.234:3000/"
end

app/models/person.rb
class Person < ActiveResource::Base
  self.site = "http://169.237.156.234:3000/"
end

app/models/preference.rb
class Preference < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :questions
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions
  has_many :eligibilities

  accepts_nested_attributes_for :questions, :allow_destroy => true
  
  attr_accessible :title, :description, :status, :deadline, :questions_attributes
  
  def owner
    Person.find(owner_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

  def contact
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  # GET /surveys
  # GET /surveys.xml
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.xml
  def show
    @survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.xml
  def new
    @survey = Survey.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.xml
  def create
    @survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to(@survey, :notice => 'Survey was successfully created.') }
        format.xml  { render :xml => @survey, :status => :created, :location => @survey }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @survey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.xml
  def update
    @survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to(@survey, :notice => 'Survey was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @survey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.xml
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to(surveys_url) }
      format.xml  { head :ok }
    end
  end
  
  # GET /surveys/1/vote
  def vote
    @survey = Survey.find(params[:id])
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ballots_helper.rb
module BallotsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/ballots/_form.html.erb
<%= nested_form_for(@ballot) do |f| %>
  <% if @ballot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ballot.errors.count, "error") %> prohibited this ballot from being saved:</h2>

      <ul>
      <% @ballot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br />
    <%= f.datetime_select :deadline %>
  </div>

  <%= f.fields_for :questions do |question_form| %>
    <%= question_form.text_field :question %>
    <%= question_form.link_to_remove "Remove this question" %>
  <% end %>
  <p><%= f.link_to_add "Add a question", :questions %></p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ballots/vote.html.erb
<p id="notice"><%= notice %></p>

<% if @ballot.status == false %>

	<p>This ballot has expired.</p>

<% else %>

	<h3><%= @ballot.title %></h3>

	<p>
	  <i><%= @ballot.description %></i>
	</p>

	<p>
	  <b>Notice:</b> This ballot will close at <%= @ballot.deadline %>.
	</p>

	<p>
	  <b>Questions:</b>
	  <ul>
		<% for question in @ballot.questions %>
		  <li>
		    <%= question.question %><br />
		    <ol style="list-style-type: none;">
			  <li><input type="radio" name="question_<%= question.id %>" value="yes" /> Yes</li>
			  <li><input type="radio" name="question_<%= question.id %>" value="no" /> No</li>
			  <li><input type="radio" name="question_<%= question.id %>" value="decline" /> Decline</li>
			</ol>
		  </li>
		<% end %>
	  </ul>
	</p>
	
	<p>
	  <input type="submit" method="POST" value="Submit" />
	</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DssEvote</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults, "nested_form" %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/site/contact.html.erb
<h1>Site#contact</h1>
<p>Find me in app/views/site/contact.html.erb</p>

app/views/site/index.html.erb
<h1>Site#index</h1>
<p>Find me in app/views/site/index.html.erb</p>

app/views/surveys/_form.html.erb
<%= nested_form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br />
    <%= f.datetime_select :deadline %>
  </div>

  <%= f.fields_for :questions do |question_form| %>
    <%= question_form.text_field :question %>
    <%= question_form.link_to_remove "Remove this question" %>
  <% end %>
  <p><%= f.link_to_add "Add a question", :questions %></p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<h1>Listing surveys</h1>

<table>
  <tr>
	<th>Description</th>
    <th>Status</th>
    <th>Deadline</th>
    <th>No. Questions</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @surveys.each do |survey| %>
  <tr>
	<td><%= survey.description %></td>
    <td><%= survey.status %></td>
    <td><%= survey.deadline %></td>
    <td><%= survey.questions.count %></td>
    <td><%= link_to 'Show', survey %></td>
    <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
    <td><%= link_to 'Destroy', survey, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @survey.description %>
</p>

<p>
  <b>Status:</b>
  <%= @survey.status %>
</p>

<p>
  <b>Deadline:</b>
  <%= @survey.deadline %>
</p>

<p>
  <b>Questions:</b>
  <ul>
	<% for question in @survey.questions %>
	  <li><%= question.question %></li>
	<% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/vote.html.erb
<p id="notice"><%= notice %></p>

<% if @survey.status == false %>

	<p>This survey has expired.</p>

<% else %>

	<h3><%= @survey.title %></h3>

	<p>
	  <i><%= @survey.description %></i>
	</p>

	<p>
	  <b>Notice:</b> This survey will close at <%= @survey.deadline %>.
	</p>

	<p>
	  <b>Questions:</b>
	  <ul>
		<% for question in @survey.questions %>
		  <li>
		    <%= question.question %><br />
		    <ol style="list-style-type: none;">
			  <li><input type="radio" name="question_<%= question.id %>" value="yes" /> Yes</li>
			  <li><input type="radio" name="question_<%= question.id %>" value="no" /> No</li>
			  <li><input type="radio" name="question_<%= question.id %>" value="decline" /> Decline</li>
			</ol>
		  </li>
		<% end %>
	  </ul>
	</p>
	
	<p>
	  <input type="submit" method="POST" value="Submit" />
	</p>

<% end %>